## Tugas 3 - Reinforcement Learning ##
### Q-Learning ###
##### Febry Ghaisani 1301154576 IF3902 #####

Analisis coming soon...

In [476]:
import pandas as pd
import numpy as np
import random

In [477]:
datas1 = np.genfromtxt('DataTugasML3.txt', delimiter='\t',dtype=int)
datas2 = np.zeros((10,10,2))

k = 0
for i in range(10):
    for j in range(10):
        c = datas1[i,j]
        d = np.array([k,c])
        datas2[i,j] = d
        k += 1
# print(datas2)

Q = np.zeros((4,100))
# Q[Q == 0] = -100

In [478]:
def get_coor_by_action(random,x,y):
    if random == 0:
        x -= 1
        if x<0:
            x += 1
    elif random == 1:
        y += 1
        if y>9:
            y -= 1
    elif random == 2:
        x += 1
        if x>9:
            x -= 1
    elif random == 3:
        y -= 1
        if y<0:
            y += 1
    return x,y

In [479]:
# Exploration

alpha = 0.1
gamma = 0.9

for j in range(600):
    x = 9
    y = 0
    s = 90
    
#     reward = 0
#     arah = []

    while (x != 0 & y != 9):
        # random action, N=0 S=2 W=3 E=1
        pol = np.random.choice(4, 1)
        x,y = get_coor_by_action(pol,x,y)
    
        # update table Q
        maks = np.amax(Q, axis=0)
        Q[pol,s] = (Q[pol,s] + (alpha*(datas2[x,y][1]+(gamma*maks[int(datas2[x,y][0])]) - Q[pol,s])))
        
        # next state
        s = int(datas2[x,y][0])
        
#         arah.append(pol)
#         reward += datas2[x,y][1]
#     print('reward tiap episode ke : ',j,reward)
# print(Q)

In [480]:
# Exploitation

st = 90
xt = 9
yt = 0
rew = 0
state = []

while (st != 9):
    # get max a', Q(s',a')
    makst = np.amax(Q, axis=0)
    pola, st = np.where(Q == makst[st])
    if (pola.size > 1):
        pol = pola[0]
    else:
        pol = pola
        
    xt,yt = get_coor_by_action(pol,xt,yt)
    # next state
    st = int(datas2[xt,yt][0])
    
    state.append(st)
    rew += datas2[xt,yt][1]
    
print(rew)
print(state)

61.0
[80, 81, 82, 83, 84, 74, 64, 54, 44, 45, 46, 47, 37, 38, 28, 29, 19, 9]


In [329]:
# ------------------------------------------ UNUSED ------------------------------------------

import numpy as np
a = np.array([[np.array([1,2]),2,3],[np.array([2,3]),5,3]])
a[0,0][:]

data = np.zeros((10,2))
datas2 = np.vstack(([np.zeros((10,2))],[np.zeros((10,2))]*9))
# np.insert(datas2,np.zeros((10,2)))
datas2

# b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.zeros((1,3,3))
print(b)
b[b == 0] = -10
b

[[[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]]


array([[[-10., -10., -10.],
        [-10., -10., -10.],
        [-10., -10., -10.]]])